### PR TITLE
Adding getPopular

### PR DESCRIPTION
**Pull request by jonneguyt**
Addressing issue #3 
My first real try at this...

Can you check and update accordingly?

I may have not really utilized all options (also new to github).

Cheers!

### CODE REVIEW

**Comment by pablobarbera** [comment]
Thanks again, this is so great! I made some minor changes to the names of the data frame so that it's consistent with the other functions and what the API returns. I also added you as contributor to the package. :-)

**Comment by jonneguyt** [comment]
Cool! Thanks for the efforts so far, a useful and nice package. Are there any other things you would like to see implemented?

**Comment by pablobarbera** [comment]
I appreciate it! I think the only thing that I wanted to look at before doing the CRAN release is adding the min_timestamp and max_timestamp in the searchInstagram function to search during specific times during the past few days (issue #1, but I think the parameter names changed). But last time I checked I found it very confusing... but that's pretty much it, all the other endpoints are already in the package, I think.

**Comment by jonneguyt** [comment]
I think they some endpoints have been added. Logging off for today, may revisit this somewhere next week (after PhD defense..). I believe there is room for some additional functions (and also some more documentation). I have not worked with any input parameters yet, but might give that a go too.

I will try to bundle the next set of pull requests.

**Comment by pablobarbera** [comment]
Sounds good. Good luck in your defense!

**Pull request merged**
